"""add segments topics transcript_source chat_messages note_translations

Revision ID: bee22df18c7c
Revises: ee62099fbc03
Create Date: 2026-09-16 00:45:14.905690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bee22df18c7c'
down_revision: Union[str, Sequence[str], None] = 'ee62099fbc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='check_chat_role'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_video_id'), 'chat_messages', ['video_id'], unique=False)
    op.create_table('note_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("language IN ('en', 'ar')", name='check_translation_language'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_translations_id'), 'note_translations', ['id'], unique=False)
    op.create_index(op.f('ix_note_translations_video_id'), 'note_translations', ['video_id'], unique=False)
    op.add_column('processed_contents', sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('processed_contents', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('processed_contents', sa.Column('transcript_source', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_contents', 'transcript_source')
    op.drop_column('processed_contents', 'topics')
    op.drop_column('processed_contents', 'segments')
    op.drop_index(op.f('ix_note_translations_video_id'), table_name='note_translations')
    op.drop_index(op.f('ix_note_translations_id'), table_name='note_translations')
    op.drop_table('note_translations')
    op.drop_index(op.f('ix_chat_messages_video_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
